return to contest and task page from verdict
johnnovikov/MSHP-CTF pull request #11
Opened 2021-01-12 23:17 UTC by Gosunov

Ну я попытался сделать возвращение к контесту сразу после получения вердикта. Вроде работает

2021-01-12 23:40 UTC, Gosunov commented on app/views/base_views.py
> +    contest_id = get_contest_id_by_task(task)
ой, наверное, эту строчку ниже надо, после проверки что таск не нулл

2021-01-19 11:59 UTC, jnovikov requested changes

2021-01-19 11:59 UTC, jnovikov commented on app/__init__.py
> -
Куда ушла строка ?

2021-01-19 11:59 UTC, jnovikov commented on .vscode/settings.json
> +}
vscode должен быть в гитигноре / не коммить его

2021-01-19 11:59 UTC, jnovikov commented on test.py
> +import sys
Что это ?

2021-01-19 11:59 UTC, jnovikov commented on app/views/base_views.py
> +    contest_id = get_contest_id_by_task(task)
Ага

2021-01-19 11:59 UTC, jnovikov commented on app/controllers/task_controller.py
> +    contest_task = ContestTask.query.filter_by(task_id=task['id']).first()
Это не очень будет работать потому что один и тот же таск может быть в нескольких контестах.

Как надо сделать: 

1) При заходе на таск нужно просто знать из какого контеста мы пришли.
Как это можно сделать: 
а)  Положить в сессию id контеста при заходе на страницу контеста
б) Добавлять get-параметр ?from_contest=<id> на страничку таска при переходе с контеста (так лучше даже наверное)
2) После этого написать логику, что если мы знаем из какого контеста пришли и таск решен верно, то автоматически редиректить на страничку контеста (лучше сделать это через JS с таймером красивым)
Если таск решен неправильно, то также автоматом редиректить на страничку таска (через JS с таймером для красоты тоже)

2022-04-26 16:33 UTC, closed without merging